### ISSUE TITLE
E: Unable to load /home/azguolu/download/pin-3.5/source/tools/pinfi/obj-intel64/instcount.so: dlopen failed: cannot locate symbol "_Z14isInstFITargetN10LEVEL_CORE5INDEXILi6EEE" referenced by "/home/azguolu/download/pin-3.5/source/tools/pinfi/obj-intel64/instcount.so"

### ISSUE THREAD

**Issue by kakulo** [DependableSystemsLab/pinfi#2]
Hi There,

I am using your PINFI tool to do fault injection into programs. 
But I get this wrong information from the program output and the baseline output.

"
az@n02: cat prog_output/outputfile-0 
E: Unable to load /g/g90/guo7/programs/pin-3.5/source/tools/pinfi/obj-intel64/faultinjection.so: dlopen failed: cannot locate symbol "_Z14isInstFITargetN10LEVEL_CORE5INDEXILi6EEE" referenced by "/g/g90/guo7/programs/pin-3.5/source/tools/pinfi/obj-intel64/faultinjection.so"...

az@n02:  cat baseline/golden_output 
E: Unable to load /home/azguolu/download/pin-3.5/source/tools/pinfi/obj-intel64/instcount.so: dlopen failed: cannot locate symbol "_Z14isInstFITargetN10LEVEL_CORE5INDEXILi6EEE" referenced by "/home/azguolu/download/pin-3.5/source/tools/pinfi/obj-intel64/instcount.so"...
"
az@n02: cat error_output/errorfile-0 
Program crashed, terminated by itself, return code 255

Do you have any idea how to solve this issue? 

Thanks,
Lenny

**Comment by flyree** [comment]
Hi Lenny,

Thank you for using pinfi. The problem is caused by upgrading to pin-3.5. We have fixed the issue, and the latest code is on github now. 

Bo

**Comment by kakulo** [comment]
Hi Bo,

Great! Thanks for the help. Take care!

Lenny
