### ISSUE TITLE
pinfi not working with latest version of pin tool

### ISSUE THREAD

**Issue by ttgrant** [DependableSystemsLab/pinfi#4]
appears the last version supported for pin tool was 3.5 however I can only seem to find access to the current version 3.16 for linux. Is there a possibility this will be updated for the current version or where could i get pin tool 3.5 for linux.

**Comment by karthikp-ubc** [comment]
We have a version of pin 3.5 that you can download to run PINFI. Please send me an email at karthikp@ece.ubc.ca and I'll send you the link to download it from. Thanks.

**Comment by vmatos-shiratech** [comment]
As of today, you can still download [pin 3.5 on this link](https://software.intel.com/sites/landingpage/pintool/downloads/pin-3.5-97503-gac534ca30-gcc-linux.tar.gz).
